#include "serial.h"

/*
 * Enable the Serial Communication
 * Note: need to set and use timer1
 */
void UartInit(void)		//4800bps@11.0592MHz (generated by STC-ISP)
{
	PCON |= 0x80;		//使能波特率倍速位SMOD
	SCON = 0x50;		//8位数据,可变波特率
	//AUXR &= 0xBF;		//定时器1时钟为Fosc/12,即12T
	//AUXR &= 0xFE;		//串口1选择定时器1为波特率发生器
	TMOD &= 0x0F;		//清除定时器1模式位
	TMOD |= 0x20;		//设定定时器1为8位自动重装方式
	TL1 = 0xF4;		//设定定时初值
	TH1 = 0xF4;		//设定定时器重装值
	ET1 = 0;		//禁止定时器1中断
	TR1 = 1;		//启动定时器1
    EA = 1;         //开总中断
    ES = 1;         //开UART中断(用于单片机收发串口数据的中断处理)
}

void UartSendMsg(char *msg)
{
    while(0 != *msg) {
        UartSendByte(*msg);
        msg++;
    }
}

/*
 * UART interrupt is mainly used for receive(distinguish 
 * between transmission and receivision by flag TI and RI) 
 */
void UART_Routine() interrupt 4
{
    uint8_t c;
    if (1 == RI) {
        c = SBUF;
        RI = 0; //software reset to 0
#ifdef UART_REFLECTION_MODE
        UartSendByte(c); //default action for receivision: reflection
#else
        /*handle*/
#endif
    }
}
